### ISSUE TITLE
Noise filtering and numerical derivatives

### ISSUE THREAD

**Issue by andreadelprete** [robotology/codyco-modules#11]
Filtering noise in sensor outputs and computing numerical derivatives are fundamental steps in the implementation of most controllers. Currently I'm using 1st order IIR low pass filters for noise filtering (see [FirstOrderLowPassFilter](http://wiki.icub.org/iCub/main/dox/html/classiCub_1_1ctrl_1_1FirstOrderLowPassFilter.html#_details)) and adaptive windows polynomial fitting for computing numerical derivatives (see [adaptWinPolyEstimator](http://wiki.icub.org/iCub/main/dox/html/group__adaptWinPolyEstimator.html)). Both are implemented in the C++ library [ctrlLib](http://wiki.icub.org/iCub/main/dox/html/group__ctrlLib.html), which is part of the iCub repository. 
# Current Issues

The reasons why I am not happy with the current solution are:
- computation time is too large (mainly due to dynamic memory allocation)
- better noise attenuation could be achieved with higher order and more advanced filters (e.g. Chebyshev, Butterworth, elliptic)
- polynomial fitting provides only moderate high frequency attenuation (see this [paper](http://www-inst.eecs.berkeley.edu/~ee123/fa12/docs/SGFilter.pdf) for details) and I suspect that the adaptive window size does not improve this aspect
# Proposed solution

I would like to replace these classes with more advanced filter implementations, with particular focus on computation time (since these filters should be used inside real-time control loops). Rather than implementing a digital signal processing library from scratch I'd like to use an existing library. Although clearly thought for audio filtering, the C++ library [DSPFilters](https://github.com/vinniefalco/DSPFilters) seems particularly interesting, because of the following features:
- Butterworth, Chebyshev, Elliptic, Bessel and Legendre filters
- any type of frequency filtering (Low Pass, High Pass, Band Pass, Band Stop)
- smooth interpolation of filter settings (e.g. cut frequency) to achieve seamless parameter changes
- no calls to malloc or new, great for embedded systems
- no external dependencies, just the standard C++ library
- GUI with charts to show magnitude, phase response and pole/zero placement of any filter

My intention is to test this library and, if the results are satisfactory, start using it in the iCubWholeBodyState class. 
##### Note on numerical derivatives

The library provides no direct method for numerical derivative computation, but once the input signal has been filtered to attenuate noise, numerical derivatives can be safely computed through exact polynomial fitting (e.g. fitting a 3rd order polynomial to a 4-point moving window).
### Other references

Just for the records, I report here other interesting libraries I found in my research. 
- [mkfilter](http://www-users.cs.york.ac.uk/~fisher/mkfilter/) C++ library with web-based front-end, Butterworth, Bessel or Chebyshev IIR filters, with lowpass, highpass, bandpass or bandstop characteristcis, designed by bilinear transform or matched z-transform method; IIR bandpass, bandstop (notch) or allpass resonators, designed directly in the z-plane; FIR raised-cosine filters, optionally with a square-root response; FIR Hilbert transformers.
- [Butterworth filter design](https://github.com/ruohoruotsi/Butterworth-Filter-Design):   C++ classes for high order Butterworth IIR and EQ filters using the bilinear transform; generated filter coefficients are split out into cascaded biquad sections, for easy use in any biquad or second-order section (SOS) implementation.
- [spuc](http://spuc.sourceforge.net/): C++ library for DSP Simulation/Modeling

**Comment by traversaro** [comment]
In a sense, this long discussion is now being solved in https://github.com/robotology/WB-Toolbox/issues/46 , by moving all the filtering **out** of the interface rather than hidden in the interface. This decision was taken because most of the user of WBI and WB-Toolbox were not aware of the existence of this filters, as they were hidden inside they interface.
