### ISSUE TITLE
[TorqueBalancing] Clean up module

### ISSUE THREAD

**Issue by francesco-romano** [robotology/codyco-modules#114]
The module was thought with the CoDyCo Y1 demo in mind.
New requirements now ask for cleaning up the module and transform it into a generic balancing module

Tasks are:

- [x] create and reads external references through RPC port
- [x] remove the old embedded FSM
- [x] handle contraints changes 
- [x] robustify start/stop switching: when the controller is started references must be reset to the actual values
- [x] adding an `events:o` port to raise events
- [x] Removing hardcoded world to base homogenous transformation.  
- [x] Add the ability to bypass the trajectory generator in the PID controller (useful for example when setting a new reference to coincide with the current measure)

**Comment by traversaro** [comment]
* [ ] adding an `events:i` port to raise events  (to be discussed) ?

**Comment by francesco-romano** [comment]
`events:o` ? Anyway, +1

**Comment by traversaro** [comment]
Just for refence: the place holder functions for activating/deactivating contacts in lua are: https://github.com/robotology/codyco-modules/blob/master/src/modules/graspAndStepDemo/lua/gas_funcs.lua#L28 . Obviously we are free to change them.

**Comment by traversaro** [comment]
* [ ] remove references to the "hand" end-effectors (until we have the link-generic constraint support)?

**Comment by traversaro** [comment]
ref https://github.com/robotology/codyco-superbuild/issues/61

**Comment by francesco-romano** [comment]
All the tasks have been completed, or they are no longer needed. 
Closing this issue.
