### ISSUE TITLE
Find a way to easily put the robot in a desired configuration

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-modules#115]
Currently we are using the `yarpmotorgui`, but it takes a lot of time from being in the terminal with the joint position file available, to actually set the robot in a desired configuration (30 secs? 1 min?). 

The easiest way to solve this is probably to improve the `yarpmotorgui` usability.

**Comment by francesco-romano** [comment]
But.. what's the status of `yarpmotorgui` ?

**Comment by traversaro** [comment]
?

**Comment by francesco-romano** [comment]
I was meaning: is it useful? Have we tried to load a sequence in it and see how it behaves?
ect..

**Comment by traversaro** [comment]
`yarpmotorgui` is just the new names of `robotMotorGui` on yarp machine where Qt5 is not installed. 
For the Qt5 version, @DanielePucci did some testing.

**Comment by traversaro** [comment]
Providing a custom 'yarpmotorgui' configuration file with a custom home seems already to be a much better solution, as suggested by @DanielePucci

**Comment by traversaro** [comment]
Adding the `yarpmotorgui` configuration files in the robots-specific file of torqueBalancing is a satisfying solution for now ( https://github.com/robotology/codyco-modules/commit/b5e14dc005b5ab7d8a533d2f27aa25d984b57ff3 ), closing for now.
