### ISSUE TITLE
quaternionEKF - IMU not very reliable

### ISSUE THREAD

**Issue by naveenoid** [robotology/codyco-modules#125]
Preliminary tests using just the xsens placed on perfectly flat ground give varying readings. Over trials of 30 seconds each, there were differences of over 0.5 degree between trials on average. Differences cannot be explained due to randomness as the variance of each trail was equal. Can submit plots to justify this observation. 

Not sure if its the IMU api or something  else.

**Comment by jeljaik** [comment]
This was solved with the latest version of quaternionEKF in which yarpdev is used instead of the hand-made driver.
