### ISSUE TITLE
[wholeBodyDynamicsTree] The parameter "cutoff" in wholeBodyDynamics.ini is ineffective 

### ISSUE THREAD

**Issue by DanielePucci** [robotology/codyco-modules#128]
The parameter "cutoff" in the configuration file wholeBodyDynamicsTree.ini is ineffective.

**Comment by traversaro** [comment]
Actually it is effective, it changes the cutoff frequency of the only low-pass filter that is executed in the wholeBodyDynamicsTree, the one that filters IMU measurements.

**Comment by DanielePucci** [comment]
Then, as we discussed, changing the name of the parameter may help users to understand better its meaning. Otherwise, one may be confused by its name, and assume that other measurements arriving to the module, e.g. those from the FT sensors, are also filtered.

**Comment by traversaro** [comment]
`cutoff` was documented both in the help message and in the doxygen documentation (not updated due to https://github.com/robotology/codyco-superbuild/issues/80 ). 
By the way, this issue should be solved by https://github.com/robotology/codyco-modules/pull/129 .. can you check it ?

**Comment by DanielePucci** [comment]
It seems to me that in the help message, it was not specified that ~~cutoff~~ was for the IMU measurements only, i.e.

~~~
[INFO]	--cutoff           :cutoff frequency (in Hz) of the low pass filters used in wholeBodyDynamicsTree. 
~~~

Anyways, I'll check the fix soon. Thanks a lot Si :+1:

**Comment by traversaro** [comment]
The only filters in the module where the ones for the IMU measurements, so the documentation was correct (and consistent with the old wbd). I was wrong in remembering the filter that where implemented in the module.

**Comment by DanielePucci** [comment]
I checked the effect of 
~~~
cutoff_ft 
~~~
while performing a trajectory tracking (qd(t) = 10° sin(0.5Hz t) ) through a computed-torque control.

Here are the results.
~~~
No cutoff_ft in wholeBodyDynamicsTree.ini 
~~~
R_leg FT measurements

![measrlegftnofilter](https://cloud.githubusercontent.com/assets/5045846/8979570/07940a14-36ab-11e5-9220-0cacef1647c1.png)

Torque tracking

![torquetrackingnofilter](https://cloud.githubusercontent.com/assets/5045846/8979579/162eede6-36ab-11e5-846d-3307e05011e0.png)

~~~
cutoff_ft 3.0
~~~

R_leg FT measurements

![measrlegft3hzfilter](https://cloud.githubusercontent.com/assets/5045846/8979587/2dd45c60-36ab-11e5-9e68-552bee26636f.png)

Torque tracking

![torquetracking3hzfilter](https://cloud.githubusercontent.com/assets/5045846/8979590/343e2b4e-36ab-11e5-8d22-e0c959ab664f.png)
