### ISSUE TITLE
Compliant foot planting on angled surfaces

### ISSUE THREAD

**Issue by naveenoid** [robotology/codyco-modules#130]
Issue to track the tasks needed to investigate compliant foot planting under uncertainty on surface orientation.
- [ ] Cartesian solver for the 2 legs to move from double stable phase to single foot planting (@traversaro  and naveen)
- [x] Exposing of impedance control interface (@francesco-romano )
- [ ] Setup of gazebo with the angled surface block object (naveen)
- [ ] Setup of experiment data gathering scripts (naveen)

**Comment by traversaro** [comment]
For the first bullet point, please check : https://github.com/robotology/codyco-modules/issues/107 .

**Comment by francesco-romano** [comment]
Second point has a separate issue: https://github.com/robotology-playground/yarp-wholebodyinterface/issues/41

**Comment by francesco-romano** [comment]
Interaction mode implemented for a single joint in https://github.com/robotology-playground/yarp-wholebodyinterface/commit/8a24605ef3956591edba90a99687a73abeed0245

**Comment by traversaro** [comment]
Research actively successfully published in  http://ieeexplore.ieee.org/abstract/document/7803270/ , closing the issue.
