### ISSUE TITLE
[T03] Raw data acquired through the wholeBodySensors should be used to populate iDynTree::SensorsMeasurements

### ISSUE THREAD

**Issue by jeljaik** [robotology/codyco-modules#147]
This is a tentative ordered list of tasks. Nevermind detailed explanations on each..once done, yarpWholeBodySensors will be able to parse the MTB sensors. NOTE : In this version, only MTB Accelerometer and Gyroscopes readings will be used within SensorsMeasurements. Existing sensors data (except accelerometers) will be acquired in their current Vector versions to retain initial backward compatibility.

Checklist of tasks
- [x] new sensors in wbi_constants
- [x] new IDList objects corresponding to new sensors
- [x] LoadAccelerometerFromConfig modification
- [x] LoadGyroscopeFromConfig implementation
- [x] Read config from yarpWholeBodyInterface.ini
- [x] yarpWholeBodyInterface.ini modification (enabled sensor information)
- [x] wholeBodySensorTester CodycoModules
- [x] wholeBodySensorTester thread
- [x] Open wholeBodySensor on Tester and pass RF
- [x] code to distinguish MTB and IMU accelerometer / gyroscope
- [x] MTB/IMU Accelerometer and Gyro opening
- [x] readGyroscope / read Accelerometer methods update
- [x] iCubGenova02 sensorised - sanity check
- [x] yarp stream parsing test (using dataset player)
- [x] Documentation

**Comment by jeljaik** [comment]
@naveenoid I'm positive many of these tasks have already been done, am I right? :) If so, can you please update?

**Comment by naveenoid** [comment]
Ongoing..I am hoping to have it complete soon (4-5 days max). Next commits in my branch will update the existing structure.

**Comment by naveenoid** [comment]
sensor tester module : https://github.com/robotology/codyco-modules/pull/169

**Comment by traversaro** [comment]
Closing for cleanup of old issues.
