### ISSUE TITLE
icubWholeBodyActuators::setControlMode controlMode is not correctly updated on all joints

### ISSUE THREAD

**Issue by francesco-romano** [robotology/codyco-modules#15]
Method `icubWholeBodyActuators::setControlMode` called for all joints.
The controlMode (`currentCtrlModes`) map update can be skipped: see the following code:

```
switch(controlMode)
    {
        case CTRL_MODE_POS:
            FOR_ALL(itBp, itJ)
                if(currentCtrlModes[LocalId(itBp->first,*itJ)]!=controlMode)
                    ok = ok && icmd[itBp->first]->setPositionMode(itBp->first==TORSO ? 2-(*itJ) : *itJ);
            break;
.....
    }
    if(ok)
    {
        FOR_ALL(itBp, itJ)
            currentCtrlModes[LocalId(itBp->first, *itJ)] = controlMode;
        if(ref!=0)
            ok = ok && setControlReference(ref);
    }
```

If for the i-th joint the set*Mode returns false, then all subsequent updates are skipped, and the variable `ok` is false. But the first i joints are still in another control mode.
I think the map update should be done contextually to the set function call.

**Comment by traversaro** [comment]
Deprecating as we are migrating to the ControlBoardRemapper class, whose handling of single joint failures will be in line with the rest of YARP software.
