### ISSUE TITLE
Directory/File names with a `:` are not valid paths in Windows 

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-modules#152]
See https://ci.appveyor.com/project/traversaro/codyco-superbuild/build/1.0.239 and https://github.com/robotology/codyco-modules/tree/master/src/modules/quaternionEKF/data/dumper01/icub/right_leg/state:o . 

cc @jeljaik

**Comment by traversaro** [comment]
cc @jeljaik

**Comment by jeljaik** [comment]
But these are automatically generated by datadumper :/

**Comment by jeljaik** [comment]
Fixed in: https://github.com/robotology/codyco-modules/commit/50926a0ab8a64273b40a785d05cea71dae292f3e
