### ISSUE TITLE
[jointTorqueControl] launch with Gazebo

### ISSUE THREAD

**Issue by rlober** [robotology/codyco-modules#170]
How do I launch JTC with Gazebo?

**Comment by francesco-romano** [comment]
Do you need it?
Gazebo already implements to torque control

**Comment by rlober** [comment]
Hey @francesco-romano 

I want to test JTC specific PID param setting/getting. #168 

Just for testing, not for actual control.

**Comment by francesco-romano** [comment]
Ok. That was the second option :smiley: 

Have you tried something?
Like copying and pasting the configuration on the yarpmanager for the robot?
There already exist the configuration files for gazebo (even if I think the coupling should be removed).

**Comment by rlober** [comment]
As of now, I haven't tried anything yet. I actually am not sure how the Gazebo plugins load `.ini` files - if at all?

**Comment by francesco-romano** [comment]
You can launch it as a module. Take a look on how it is launched on the real robot.

**Comment by rlober** [comment]
Thanks fra I will give it a shot and let you know

**Comment by rlober** [comment]
Hey man. Looks like I just had to launch the module as you said there are even `.ini` files already made for `icubGazeboSim`. 

For future reference.
```
codycomoddev --from jtc_[part_name].ini
```

thanks @francesco-romano

**Comment by francesco-romano** [comment]
Great!
One thing I noticed is that there are coupling matrices in the .ini file.
To test set/get they are not an issue, but otherwise they should be removed I think
