### ISSUE TITLE
Get external wrenches estimation to work on the Walkman robot

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-modules#200]
@gabrielenava has been recently struggling to get the estimation of external wrenches to work on the Walkman robot, using the old KDL-based `wholeBodyDynamicsTree`. He got stuck on several points in which the code was hardcoding iCub-specific information. 

The last bug of this kind was the hardcoding of the `imu_frame` name as the frame in which the IMU outputs its measurements. While it could be possible to update the old `wholeBodyDynamicsTree`, I think it would be a waste of resources. The new `wholebodydynamics` device can be easily run outside the main `yarprobotinterface` program of the robot using the new module `wholeBodyDynamics3` (pun intended), so I think it is easier to just put effort in improving the new software. 
The `wholeBodyDynamics3` is a sort of little `yarprobotinterface` (actually in the future it could be replaced with a dedicated configuration of the `yarprobotinterface`), i.e. it launches several YARP devices and connects them appropriately. An example configuration file for `icubGazeboSim` is https://github.com/robotology/codyco-modules/tree/master/src/modules/wholeBodyDynamics3/app/robots/icubGazeboSim . The only problem is that at the moment `wholebodydynamics` to run needs some features only available in the `devel` branch of YARP, but I think we can start to work on it with @gabrielenava and wait for the release of YARP 2.3.68 to switch to `wholeBodyDynamics3` for all the codyco users.

**Comment by traversaro** [comment]
I am going through the code to see if there some robot-specific leftovers (beside https://github.com/robotology/codyco-modules/issues/199).

**Comment by traversaro** [comment]
At the moment this issue is blocking: https://github.com/robotology/idyntree/issues/230 .

**Comment by traversaro** [comment]
> actually in the future it could be replaced with a dedicated configuration of the yarprobotinterface

Note that this happened.

**Comment by gabrielenava** [comment]
Being the activity on Walkman not carried on at the moment, maybe we can close this issue. Also, I think this issue is now outdated.

**Comment by traversaro** [comment]
I agree.
