### ISSUE TITLE
Cannot connect to WBDT rpc

### ISSUE THREAD

**Issue by hu-yue** [robotology/codyco-modules#210]
After updating everything to the devel branch (yarp, icub-main, firmware) in order to use the floating base estimation, we are now not able to connect to the rpc of `wholeBodyDynamicsTree` anymore.
When doing `yarp rpc /wholeBodyDynamicsTree/rpc:i` nothing happens and it seems that the connection is not being established.

@traversaro

**Comment by traversaro** [comment]
Mh... Have you recompiled the `codyco-superbuild` and in particular `codyco-modules` after the massive update to the `devel` branch?

**Comment by hu-yue** [comment]
Yes, and just to be sure I just did it again, and I still have the same issue. But we can connect using another computer plugged in the network (and on which we did no update anything)

**Comment by hu-yue** [comment]
Uhm ok I think it's a stupid issue, sorry, the thing is that before when you open rpc there was `>>` as waiting for the input command, now it's not there and it seemed nothing was happening... I just tried to type in commands and it's working.
