### ISSUE TITLE
Merging of unused branches into master

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-modules#23]
Apparently there are some non-trivial (at least for me) conflicts when trying to merge branch module/adaptiveControl in to master . 
Could you look into it @francesco-romano ? Thanks.

**Comment by francesco-romano** [comment]
Let's ping again.
There are 17 branches right now.

@traversaro

**Comment by traversaro** [comment]
As this repo will be archive, I think we can simply close this issue.
