### ISSUE TITLE
jointTorqueControl needs to be ported to use the new IPWMControl interfaces 

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-modules#230]
The only place where I am aware of it use is on `iCubParis*`, so it is not urgent because those robots use the `master` branch of `yarp`, but it must be completed before the next release of YARP.

**Comment by traversaro** [comment]
cc @DanielePucci

**Comment by DanielePucci** [comment]
I think that this may be a task for @diegoferigo according to his current workload.

**Comment by diegoferigo** [comment]
@DanielePucci What is the status of this task? Is it still something where we want to invest time?

**Comment by traversaro** [comment]
fyi @lrapetti

**Comment by traversaro** [comment]
I think we can drop support for the `jointTorqueControl` device present in this repo. If the need emerge, we can still update it in the future.
