### ISSUE TITLE
wholeBodyDynamicsDevice continuously emits warnings when skin is connected

### ISSUE THREAD

**Issue by francesco-romano** [robotology/codyco-modules#247]
Sorry for the image instead of textual description, but I do not have the log with me.

![2017-10-09 17 14 08](https://user-images.githubusercontent.com/2189180/31345200-4655a784-ad15-11e7-988d-5a10af65df0b.jpg)

See [this](https://github.com/robotology/codyco-modules/blob/0168f7976a6115dd23e5562f693b2b4ca6791451/src/devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp#L1415)

**Comment by traversaro** [comment]
cc @fjandrad can you look into this? Thanks!

**Comment by fjandrad** [comment]
Sure Ill take It off. Sorry for the late response


Sent from my Cyanogen phone


On Oct 9, 2017 5:22 PM, Silvio Traversaro <notifications@github.com> wrote:

cc @fjandrad can you look into this? Thanks!

**Comment by fjandrad** [comment]
Done. Solved in 85e93d68f80794d2b4107e402e944360b0d0b38d

**Comment by francesco-romano** [comment]
Thanks
