### ISSUE TITLE
[torqueBalancing]-Drift of the robot movements on its left

### ISSUE THREAD

**Issue by lpenco** [robotology/codyco-modules#258]
I'm using the torqueBalancing Controller. I'm sending some jointangles references to the robot together with the corresponding com position. I extrapolate the com position through DynTree w.r.t the root link.
When I simulate the robot tends to bend the torso to the left and to open the left arm as if the com reference was more on the left.  In what coordinate frame the torqueBalacing takes the com references (root_link and which orientation?)??? Or you think it might be a problem related to the FT sensors?

**Comment by lpenco** [comment]
I was using the C++ old version of the torqueBalancing controller that is affected by unstable zero-dynamics

**Comment by traversaro** [comment]
For more info about the zero dynamics problems of the old controlller, see https://arxiv.org/pdf/1603.04178.pdf .
