### ISSUE TITLE
wholeBodyDynamics broken on iCubGenova04

### ISSUE THREAD

**Issue by gabrielenava** [robotology/codyco-modules#261]
Together with @Yeshasvitvs we tried to run the `fast yoga demo` on `iCubGenova04`. The robot fails immediately. The measured joint torques went up to a crazy value: 2000 Nm (see the picture below).

![screenshot from 2018-04-04 19-21-14](https://user-images.githubusercontent.com/12396934/38325594-b75e5746-3843-11e8-97a7-6aa07f35a34f.png)

We checked the FT measurements both using Simulink and then directly from the yarp port, but we weren't able to see any issue (see the picture below):

![screenshot from 2018-04-04 19-50-36](https://user-images.githubusercontent.com/12396934/38325647-dc78c9f8-3843-11e8-9438-c884c9b1e6fb.png)
![screenshot from 2018-04-04 19-57-01](https://user-images.githubusercontent.com/12396934/38325649-dc94e98a-3843-11e8-8a4a-b3fe8a95d32e.png)

However, the `iCubGui` showed crazy random forces acting on the robot (see the attached GIF):

![out](https://user-images.githubusercontent.com/12396934/38326044-0bfa8f12-3845-11e8-8e8e-b40ed9135c83.gif)

We then suspected that for some reason `wholeBodyDynamics` got broken, and therefore we checked directly a wholeBodyDynamics port (`/wholeBodyDynamics/right_foot/cartesianEndEffectorWrench:o `) and this was the result:

![screenshot from 2018-04-04 20-00-02](https://user-images.githubusercontent.com/12396934/38326218-85598f66-3845-11e8-83a0-b4fad4536544.png)

There are no errors in the `yarplogger`, and `yarp`, `icub-main`, `codyco-modules`, `robots-configurations` are in `devel` branch with no local changes.

**Comment by traversaro** [comment]
There are three inputs to wbd: ft sensors, joint positions and gyro/acceleroneter of the imu. Have you checked the last two?

**Comment by gabrielenava** [comment]
I checked the joint positions and there were no spikes, but I didn't check the IMU. I will check it tomorrow.

**Comment by gabrielenava** [comment]
I checked the joints and the IMU measurements. They were fine, while in the iCubGui I saw random forces as in the gif. See attached pictures.

IMU:

![screenshot from 2018-04-05 09-53-56](https://user-images.githubusercontent.com/12396934/38353843-007fe1e6-38b8-11e8-861a-31aa986c82e2.png)

Joints:
![screenshot from 2018-04-05 09-56-00](https://user-images.githubusercontent.com/12396934/38353844-009cc306-38b8-11e8-85ea-426c80d7ad39.png)

However, I noticed strange error in the logger (generic motor error?). Maybe it is also worth to open an issue in icub-support.
![screenshot from 2018-04-05 09-57-33](https://user-images.githubusercontent.com/12396934/38353845-00b8e32e-38b8-11e8-8bd0-337e5629e88f.png)

**Comment by traversaro** [comment]
We tried two things with Luca:
  * Not using the imu, sending the `useFixedFrameAsKinematicSource` command on RPC   
  *using the xsens IMU 

In both case everything was working fine, so even if there are no crazy values in the bosch IMU, the issue is related in some way to the use of the bosch IMU.

**Comment by gabrielenava** [comment]
The issue seems related to the joint acceleration estimation for the neck joints. See https://github.com/robotology/icub-support/issues/622. Closing this issue.
