### ISSUE TITLE
Velocity-dependent effects (C*dq) seems incorrect (wbi with URDF)

### ISSUE THREAD

**Issue by francesco-romano** [robotology/codyco-modules#29]
Testing the wbi (with the model loaded from the URDF file) the velocity terms (C*dq) seems incorrect.
It can be either a problem of the URDF parser or of the wbi.
@traversaro  already found some issues in the parser. Maybe they are related.

Tested with [yarpwbiTest](https://github.com/robotology/codyco/tree/rovereto/src/tests/yarpWholeBodyInterfaceTest), model taken from [here](https://github.com/robotology/gazebo_yarp_plugins/tree/master/tutorial/model/double_pendulum), configuration file taken [here](https://github.com/robotology/codyco/tree/rovereto/src/libraries/wholeBodyInterfaceIcub/conf)

Output is
> C term is 1.761797 but should be -1.897020
> C Term is 1.825830 but should be -1.965969

**Comment by traversaro** [comment]
Closing. The bug have been solved a long time ago in our software, and perhaps now they are going to merge the PR upstream.
