### ISSUE TITLE
[icub-WholeBodyActuators] setControlReference setting the whole "part"

### ISSUE THREAD

**Issue by francesco-romano** [robotology/codyco-modules#31]
This must be tested for different configurations:
- two joints in the same part set in different controlMode
- set velocity reference on the whole part
- set position reference on the whole part

**Comment by traversaro** [comment]
The main problem with this was the setting of a subset of desired joint torques in the YARP interfaces, that was solved in https://github.com/robotology/yarp/issues/176 .
