### ISSUE TITLE
[WBI-T] Unconsistent Yarp behaviour when using Yarp compiled as a static library

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-modules#44]
Today @iron76 experienced issues in using multiple WBI Toolbox blocks that where reading and writing Yarp ports. He was using OS X 10.7 . 
The nature of the problem is still unclear, but it appears that it was related to a conflict in the use of the same static variable among the different copies of the Yarp static library included in the different blocks. 

The issue was solved by compiling Yarp as a shared library.

Until we fully understand the origin of this issue and its implications I strongly suggests that we list Yarp compiled as a shared library in the requirements  of WBI-T. A even better choice would be to enforce the availability of Yarp as a shared library during the build, but I am not sure on how to implement this build behaviour.

**Comment by francesco-romano** [comment]
Because the yarp network object implements a sort of "reference count" for the init/fini methods, the use of a static library is quite dangerous. 
We can close this issue. Yarp MUST be compiled as a shared library (and this is already mentioned in the installation guide)

**Comment by traversaro** [comment]
The issue was still open for enforcing YARP a shared library in CMake
configuration

**Comment by traversaro** [comment]
@francesco-romano do you think we need a similar check on `gazebo-yarp-plugins`?

**Comment by francesco-romano** [comment]
@traversaro I don't see the point in having yarp compiled as a static library (considering also that by default it is shared). 
So, if you want to add the check then ok. Otherwise I will stick with only documentation.
