### ISSUE TITLE
[iCubGenova01] [iCubGenova03] CAD parameters for head and root_link 

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-modules#49]
Apparently inertial values for the V2 `head` are not available in iDyn ( https://github.com/robotology/icub-main/blob/b41c73517c4ad2f7a1c346a4b391aca06585b6a1/src/libraries/iDyn/src/iDyn.cpp#L2626 ). The `root_link` is missing because the iDyn uses a fixed base model. 

The current iDyn model uses a 1.33 Kg mass for the head and a 1.2 Kg mass for the root_link . 

To get some reasonable a-priori estimate we weighted iCubGenova01 and iCubGenova03:

| iCubGenova01 | iCubGenova03 |
|---------------------|-------------------|
|             30.3          |             27.5      |

While the iDyn model was:

| iCubGenova01 | iCubGenova03 |
|---------------------|-------------------|
|     24.9449 |     22.424         |

As a workaround we adopt a mass of 3 Kg for `head` and 4.72 kg for `root_link`.

**Comment by DanielePucci** [comment]
Can we close this issue?
