### ISSUE TITLE
World to base/root transformation, velocity and acceleration

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-modules#58]
One of the weakest point in the current software architecture is the handling of the world to base/root transformation. 
As a remainder for future implementation we should:
- have an only authoritative source of the world to base transformation, for example in the form of a yarp port publishing this transformation.
- add the `getEstimate(ESTIMATE_BASE_POS , ..)` implementation to wholeBodyState and use only this call in the control code to get the world to base position.

In this way if the assumption on the world location changes we have only to modify the configuration of the component that is publishing the world to base transformation, and all code should work.

**Comment by iron76** [comment]
I assigned this to Naveen since this was the original plan. @naveenoid, can you commit on that even if you are working from a remote country :smile:

**Comment by naveenoid** [comment]
Sure! Will work on it right away :)

---
Naveen Kuppuswamy, PhD
Post-doctoral Fellow,
Cognitive Humanoids Lab,
Department of Robotics, Brain and Cognitive Sciences (RBCS),
Istituto Italiano di Tecnologia, Genova, Italy

**Comment by traversaro** [comment]
Ok, after https://github.com/robotology-playground/yarp-wholebodyinterface/commit/7381d8b8c0bd3363ac9ff35c55790f75448fd728 we now have a basic `ESTIMATE_BASE_POS` implementation in yarp-wholebodyinterface. 
To definitely remove the workaround we have in the code and switch to using the State interface instead, we have to:
  * [ ] properly orient `l_sole` in the model, so we don't need hardcoded rotations (already done in iCubHeidelberg01. 
  * [ ] add ESTIMATE_BASE_VEL estimation
  * [ ] add ESTIMATE_BASE_ACC estimation
  * [ ] document the new options added to the yarpWholeBodyState interface (you can check a prototype of documentation in the yarpWholeBodyModel class documentation)
After that, we have to migrate our software:
  * [ ] migrate WBI-Toolbox (high priority)
  * [ ] migrate wholeBodyReach (high priority)
  * [ ] migrate torqueBalancing (@francesco-romano priority)
  * [ ] migrate locomotionControl (low priority)
  * [ ] migrate wholeBodyNeckVelocity (@jeljaik priority)
  * [ ] add support for it in wholeBodyGaze (low priority)

**Comment by naveenoid** [comment]
How can we move to ESTIMATE_BASE_VEL or ESTIMATE_BASE_ACC without the probabilistic estimation framework? Is there any short-term solution apart from computing it from the kinematic ESTIMATE_BASE_POS numerically? (might be highly noisy)

**Comment by traversaro** [comment]
The key idea is briefly explained in this math pastedbin: http://mathb.in/27093?key=93543ca91e0b5f8984e2c565133a9c075afc4082 .

**Comment by traversaro** [comment]
@jeljaik can correct me, but I guess that the only place where we need the ESTIMATE_BASE_ACC is the WBI-Toolbox ?

**Comment by jeljaik** [comment]
In WBI-Toolbox we actually have just a block to estimate base velocity, not acceleration.

**Comment by naveenoid** [comment]
Im working on implementing ESTIMATE_BASE_VEL in yarpWholeBodyState right
now.

---
Naveen Kuppuswamy, PhD
Post-doctoral Fellow,
Cognitive Humanoids Lab,
Department of Robotics, Brain and Cognitive Sciences (RBCS),
Istituto Italiano di Tecnologia, Genova, Italy

**Comment by traversaro** [comment]
The ESTIMATE_BASE_ACC is something similar, but using also dJdq.

**Comment by traversaro** [comment]
Any news?
While I was updating the models generated with the old method (see https://github.com/robotology/codyco-superbuild/issues/55 ) I also added a `codyco_world_balancing` frame that can is exactly the one that we used for balancing demo until now (in this way we can avoid having strange transformation matrices hardcoded in the source code). I couldn't change the l_sole definition to match the REP-105/120 convention without breaking existing software, so for now this is a nice workaround for the time being.

**Comment by naveenoid** [comment]
Im debugging ESTIMATE_BSAE_VEL..should push shortly.

---
Naveen Kuppuswamy, PhD
Post-doctoral Fellow,
Cognitive Humanoids Lab,
Department of Robotics, Brain and Cognitive Sciences (RBCS),
Istituto Italiano di Tecnologia, Genova, Italy

**Comment by DanielePucci** [comment]
Hi guys, any news on this critical issue?

**Comment by naveenoid** [comment]
pushing today..was trying to organise the unit test folders

---
Naveen Kuppuswamy, PhD
Post-doctoral Fellow,
Cognitive Humanoids Lab,
Department of Robotics, Brain and Cognitive Sciences (RBCS),
Istituto Italiano di Tecnologia, Genova, Italy

**Comment by traversaro** [comment]
Great! Could you open a PR so se can double check the code?

**Comment by traversaro** [comment]
cc @rlober @darwinlau

**Comment by traversaro** [comment]
The first implementation by @naveenoid was merged in the `yarp-wholebodyinterface` in https://github.com/robotology-playground/yarp-wholebodyinterface/commit/85a3d30bfa1be1590b9634248bd89828109097d5 . At this point, we can migrate our software (as outline in https://github.com/robotology/codyco-modules/issues/58#issuecomment-73084506) to use `getEstimate(ESTIMATE_BASE_POS)` .

At this point, then the interface is decouple from the implementation. From the point of view of implementation if we move to support a more complex estimation scheme (for example for supporting walking) we should move the estimation to a single component (such as `wholeBodyDynamicsTree`) that then publish this information on the yarp network, and then`getEstimate(ESTIMATE_BASE_POS)` can just query this published information. This should avoid the inconsistency that is possible to have if we have N distributed and not coherent estimations.

**Comment by traversaro** [comment]
Brief recap:
 * @rlober is migrating codyco-isir module, encountering some problems, solved in https://github.com/robotology-playground/yarp-wholebodyinterface/issues/29  . 
 * @jeljaik is migrating WBI-Toolbox 
 * @francesco-romano is migrating torqueBalancing 
 * @naveenoid is doing various fixes to mexWholeBodyModel . 

The biggest inconsistency that I fear at the moment is this one: when in double support, which frame should we consider as the world? 

Currently we were (in hardcoded methods) using `l_sole` + a hardcoded rototranslation to get X-FRONT, Y-LEFT, Z-UP frame. 
Directly using `l_sole` as `WORLD_REFERENCE_FRAME` will then get a different behavior with respect to the old hardcoded methods. As a workaround, I have added a custom `codyco_balancing_world` frame to the model, that should match the one that we where using in old hardcoded methods. As soon as we properly get rid of all the uses of `l_sole` in the code, we can reorient it in the models, given that the proper orientation of all frames defined in REP-120 is X-FRONT, Y-LEFT, Z-UP . At that point we can go back to use `l_sole` as the initial world frame, now without any hardcoded rotation. 

Recap ot the steps:
  * [ ] stop using l_sole, use `codyco_balancing_world` instead
  * [ ] rotate l_sole in all models
  * [ ] use l_sole again

**Comment by jeljaik** [comment]
@traversaro @naveenoid @DanielePucci 
While migrating the WBI-Toolbox I spent some time debugging something I assumed incorrectly. @naveenoid told me that the output of `getEstimates(wbi::ESTIMATE-BASE_POS, ... )` was a 12-dim array (a pointer to that array to be more precise) where the first 3 elements correspond to the position and the last 9 to the unfolded rotation matrix. This order however does not correspond to the one used to create a `Frame` object. Since this is the class we use for roto-translations in the `wholeBodyInterface` don't you think it would be nice to have it in te same format? To recap, currently the estimate is returned as:
```bash
pos_x  pox_y  pox_z  [rot_mat]
```
But in the class `Frame` we have a constructor like:
```cpp
/** Read data from a 16-dim double array. */
inline Frame(double* d):R(d[0],d[1],d[2],d[4],d[5],d[6],d[8],d[9],d[10]){ p[0]=d[3]; p[1]=d[7]; p[2]=d[8];}
```

An agreement between these two representations would be nice I think.

**Comment by rlober** [comment]
Just a question, why does the frame constructor initialize `p[2]`=z to the 8th element of the 16x1 vector?
`p[2]=d[8]`
Shouldn't it be  `p[2]=d[11];`?

Just my two cents...
It seems like changing the `ESTIMATE_BASE_POS` output to 9x1 rot then 3x1 pos is the easiest solution given its recent development. Then the next question would be can we add a check in the frame constructor for a special case of a 12x1 entry?

**Comment by jeljaik** [comment]
You're right @rlober I forgot to mention that in my previous comment! and yes, an additional constructor could be an option too, although a bit redundant I think. I would prefer to stick to one convention. Let's wait for the others to reply.

**Comment by jeljaik** [comment]
I have another issue ... Right now, the estimate of the base pose is done assuming no input on the joint angles, but it uses the current state of the interface for the computations. In some blocks of the Toolbox, say `Inverse Dynamics` we had the possibility of providing input joint angles different from the current configuration of the robot. This was used for debugging purposes as you might recall. Am I wrong or we're currently missing this feature?

c.c. @traversaro @DanielePucci @naveenoid

**Comment by rlober** [comment]
Hey @jeljaik

Actually all I meant was something along the lines of:

**wbiUtil.h**
```
inline Frame(double* d, int size=16){
if (size==16)
    R(d[0],d[1],d[2],d[4],d[5],d[6],d[8],d[9],d[10]); p[0]=d[3]; p[1]=d[7]; p[2]=d[11];
else if (size==12)
    R(d[3],d[4],d[5],d[6],d[7],d[8],d[9],d[10],d[11]); p[0]=d[0]; p[1]=d[1]; p[2]=d[2];
else
    some error checking...
}
``` 
This would be back compatible with existing constructor usage and provide a little extra functionality for the base pos estimate.

**Comment by traversaro** [comment]
As @jeljaik mentioned, perhaps using the same convention used in the wbi::Frame constructor (and hence in the KDL::Frame, by the way) would be a good idea. 
At this point we still can still modify all the code using `getEstimates(wbi::ESTIMATE-BASE_POS, ... )` ourself. 

Beside that, we should properly document the nature of the various estimate in the iWholeBodyState doxygen documentation 

In the long term, a way of getting estimates without having to deal with raw buffers (modifying the iWholeBodyState interface) would be anyway a great solution.

**Comment by traversaro** [comment]
@jeljaik : regarding the input of inverse dynamics: if you want to use the inverse dynamics with a position state (i.e. floating base position + joint positions) that is not the one currently provided by the state estimator, you should provide as an input both the **joint position** and the **floating base position**. Automatically computing the  **floating base position** from the **joint position* assumes the knowledge that a link is fixed with respect to the inertial frame, that in general is not valid assumption.

**Comment by jeljaik** [comment]
@traversaro my  bad, I didn't explain myself well enough. I meant about the estimate of the world to base rototranslation given a desired configuration that is not the current estimator state.

**Comment by traversaro** [comment]
@jeljaik : my view on that is that is not something that in general the `iWholeBodyState` can provide. 
Think for example of flying robot: in that case probably the `getEstimates(wbi::ESTIMATE-BASE_POS, ... )` would come from the fusion of inertial sensor information, GPS and visual/LIDAR sensing. In that case, there is no relationship between the joint position configuration and the floating base position.

**Comment by rlober** [comment]
Any body have a comment on the issue @jeljaik and I brought up for the frame constructor?

**Comment by DanielePucci** [comment]
I've modified the yarpWholeBodyInterface.ini and yarpWholeBodyInterface_jtc.ini, when present, to load 

WORLD_REFERENCE_FRAME codyco_balancing_world 

(instead of l_sole) and to estimate the base position and velocity (i.e. estimateBasePosAndVel). The following robots have been modified iCubGazeboSim, iCubGenova01, iCubGenova03, iCubParis01, iCubParis02, iCubDarmstadt01 @traversaro @francesco-romano @rlober

**Comment by traversaro** [comment]
Brief recap: we did the migration to the new `l_sole/r_sole` frame orientations in `icubGazeboSim`, `iCubParis01` and `iCubParis02`. We are awaiting for migrate all other models once we are back in Genoa and we can test all the software. In the meanwhile, please stick to use `codyco_world_balancing` as the world frame, or for getting the frame with the old X-UP Y-RIGHT Z-FRONT use the `r_foot_dh_frame` and `l_foot_dh_frame`.

**Comment by naveenoid** [comment]
codyco_world_balancing works fine in forward-dynamics. Tested simple
feedforward torque trajectories.

---
Naveen Kuppuswamy, PhD
Post-doctoral Fellow,
Cognitive Humanoids Lab,
Department of Robotics, Brain and Cognitive Sciences (RBCS),
Istituto Italiano di Tecnologia, Genova, Italy

**Comment by traversaro** [comment]
cc @francesco-romano

**Comment by traversaro** [comment]
To finally close this issue, I think we can simply deprecate some modules that we don't have time to maintain. 

A possible preliminary list includes: `wholeBodyReach`, `locomotionControl`, `locomotionPlanner`, `wholeBodyNeckVelocity`, `wholeBodyGaze` . 

cc @robotology/codyco-developers  opinions?

**Comment by traversaro** [comment]
cc @iron76 any objection to consider this `modules` as "deprecated" (this will mean there are moved somewhere else and they are not compiled by the superbuild by default)?

**Comment by iron76** [comment]
Yes, proceed with deprecation.

**Comment by traversaro** [comment]
The leftover of this issue are an endless sources of pain. Marking it for the next IFI day.

**Comment by traversaro** [comment]
The new model generated in https://github.com/robotology-playground/icub-model-generator do not include `codyco_balancing_world` . We should make sure that iCubParis01/02 models are properly updated and get definitely rid of `codyco_balancing_world` (that should match now `l_sole`).

**Comment by traversaro** [comment]
We are not using anymore the wholeBodyInterface and its wholeBodyEstimate interface, and there are several activity related to estimate the base position w.r.t. to an lab-fixed frame (@prashanthr05 is the person in charge for this). However, I think we can safely close this issue.
