### ISSUE TITLE
WholeBodyInterface ID representation

### ISSUE THREAD

**Issue by andreadelprete** [robotology/codyco-modules#6]
After a long chat, @traversaro and I decided to implement other three changes to the library WholeBodyInterface:
* switch from local id (i.e. IDs composed by two int, one for the "body part" and one for the "local ID") to global id (IDs composed only by one int, so that they are unique for the whole body of the robot)
* add a string to the ID (which at the moment is only numerical) to ease the interaction with urdf/collada formats
* allow any joint serialization (at the moment IDs can only be serialized so that body parts are in increasing order)

**Comment by traversaro** [comment]
Solved in https://github.com/robotology/codyco-modules/commit/8684d8a627b5bbef6fbcd2dc52f48aa5f1e63b0d .
