### ISSUE TITLE
[wholeBodyDynamicsTree] gravityCompensator

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-modules#66]
Provide wholeBodyDynamicsTree with the stuff necessary to work with the existing gravityCompensator, and eventually write a gravityCompensatorTree module.

In this way the iDynTree-based solution can be used as a drop-in replacement for the old iDyn-based wholeBodyDynamics/gravityCompensator.

**Comment by alecive** [comment]
+1

**Comment by traversaro** [comment]
reminder for @traversaro : remember @randaz81 request.

**Comment by traversaro** [comment]
The `wholeBodyDynamicsTree` is currently in the process of being deprecated, see https://github.com/robotology/codyco-modules/blob/master/doc/force_control_on_icub.md for the documentation on how to use the latest `wholebodydynamics` YARP device, and https://github.com/robotology/codyco-modules/issues/223 for the current status of the deprecation. 

In particular, the gravity compensation functionality has been implemented in the `wholebodydynamics` device, check the device documentation in ff356ae420badf973835a7da2cf6a5d38c26d201 to see how to use it.
