### ISSUE TITLE
[WholeBodyDynamicsTree] Inconsistent measurement of joint friction

### ISSUE THREAD

**Issue by rbonghi** [robotology/codyco-modules#82]
I am using Whole Body Dynamics (WBD) and Whole Body Dynamics Tree (WBDT) to measure friction on joint (test on iCubGenova03 and iCubGenova01), but I have a problem to acquire data.

If I acquire torque and velocity in different position from same joint I measure a drift in friction, because I expect the same result for any position.

For these experiments I calibrated (WBD or WBDT) in the fixed position, I put the joint in idle and finally I moved manually near the the position calibrated.

I have attached in this issue a plot with this measures.
These experiments were carried out on iCubGenova03 (legs V1) on left leg hip pitch and I used WholeBodyDynamics (WBD) and in a second experiment I used WholeBodyDynamicsTree (WBDT).

**iCubGenova03 Whole Body Dynamics**
![icubgenova03-wbd](https://cloud.githubusercontent.com/assets/4551246/5410152/e47acb9e-81f1-11e4-9f85-86dc48f3b473.png)
**iCubGenova03 Whole Body Dynamics Tree**
![icubgenova03-wbdt](https://cloud.githubusercontent.com/assets/4551246/5410153/e4dd0caa-81f1-11e4-8fce-9d94c6c2f034.png)

I measure a drift only in WBDT. Different result in iCubGenova01 (legs V2) because I measure a drift for both, WBD and WBDT.

**iCubGenova01 Whole Body Dynamics**
![icubgenova01-wbd](https://cloud.githubusercontent.com/assets/4551246/5410287/2e605c6e-81f3-11e4-9d2f-741d3c819f9a.png)

**iCubGenova01 Whole Body Dynamics Tree**
![icubgenova01-wbdt](https://cloud.githubusercontent.com/assets/4551246/5410268/fedc03ee-81f2-11e4-8458-6304dbbf300c.png)

I think the problem is in dynamic model on robot, because I would like to measure the same result for any position of joint.

**Comment by rbonghi** [comment]
I repeat again this experiment on **iCubGenova01** and I have a significant error when I put the robot in equilibrium with a one foot or the robot is in equilibrium in double support.
**Leg - Left - Hip - Roll**
![onetwofeet](https://cloud.githubusercontent.com/assets/4551246/6092160/3632252a-aed1-11e4-9e00-77c7790d7de0.png)

I have a different offset by **3 [Nm]** in single suppport and **-7 [Nm]** in double support.

Why do I measure torques only positive or only negative friction?

**Comment by DanielePucci** [comment]
After the model for iCubGenova02 is finished, we can perform again the parameter identification, and see if this issue still arise. In the negative case, we can close it.

**Comment by traversaro** [comment]
@DanielePucci you had this problems with the new model?

**Comment by DanielePucci** [comment]
We haven't re-estimated the motor and friction parameters using the new model. Let's put this task on the to-do list.

**Comment by traversaro** [comment]
Probably it is/was a problem related to https://github.com/robotology/codyco-modules/issues/160 . Closing unless we have some action to perform related to this.
