### ISSUE TITLE
[WholeBodyDynamicsTree] Measurement error of external forces

### ISSUE THREAD

**Issue by rbonghi** [robotology/codyco-modules#83]
In iCubGenova03 I measure external forces on legs when the robot is calibrated in root_link. I have run:

```
wholeBodyDynamicsTree —-autoconnect —-head V2 —-legs V1 —-feet V2 —robot icub —-name wholebodydynamicsTree —-assume_fixed root_link —-assume_fixed_calibration root_link  
```

Different result if I use IMU.
I do not measure any external forces on wholeBodyDynamicsTree.

**Comment by traversaro** [comment]
We will track the general problem of "phantom" external forces in https://github.com/robotology/codyco-modules/issues/160 .
